In [124]:
import csv
import random
import math
import numpy as np

# Load data from CSV
filename = 'diabetes.csv'
lines = csv.reader(open(filename, "r"))
data = np.array(list(lines)[1:])
data = data.astype(float)

In [125]:
# Split dataset (training set, test set)
split_ratio = 0.8
train_size = int(data.shape[0]*split_ratio)

split_data = np.split(data, [train_size, -1])
train_data = split_data[0]
test_data = split_data[1]

print('Split {0} rows into train={1} and test={2} rows'.format(len(data), len(train_data), len(test_data)))

Split 768 rows into train=614 and test=153 rows


In [126]:
# Separate data by outcome
data0 = train_data[train_data[:, -1] == 0, :]
data1 = train_data[train_data[:, -1] == 1, :]

size0 = data0.shape[0]
size1 = data1.shape[0]

# Train model (find mean and stdev)
mean0 = # TODO
# [3.28678304 109.52369077  67.67581047  19.76558603  67.32169576 30.0394015 0.43479302  31.32668329]
mean1 = # TODO
# [  4.76995305 141.01408451  70.11737089  22.33333333 104.73239437 35.37511737 0.56850704  36.71830986]
stdev0 = # TODO
# [ 3.00042389 26.87395651 18.1297523  14.78659205 99.70119324  7.77272831 0.29993086 11.79354873]
stdev1 = # TODO
# [  3.72009371  32.72283361  21.99552512  17.80374668 139.745136 7.1216321    0.38150783  10.86474649]

# Predict test_data
pdf = lambda mean, stdev, x: scipy.stats.norm(mean, stdev).pdf(x)

result = np.zeros(test_data.shape[0]) # 0 or 1
for i, data in enumerate(test_data):
    prob0, prob1 = 0, 0
    # TODO
    if(prob0 > prob1):
        result[i] = 0
    else:
        result[i] = 1

# Check Accuracy
correct = 0
for i, data in enumerate(test_data):
    if data[-1] == result[i]:
        correct += 1
print(correct/test_data.shape[0])

(153, 9)
0.7450980392156863
